tasks:
  - name: Install AWS CLI
    env: export AWS_CLI_AUTO_PROMPT=on-partial
    command: |
      cd /workspace
       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
       unzip awscliv2.zip
       sudo ./aws/install
       aws --version



